replication:
  sources:
    - name: neoA
      type: machbase
      connection:
        scheme: http
        host: 127.0.0.1 
        port: 5654
        protocol : http
        token: xxx

  targets:
    - name: neoB
      type: machbase
      connection:
        scheme: http
        host: 127.0.0.1
        port: 6654
        protocol : http
        token: xxx

  jobs:
    - name: neoA-to-neoB
      source: neoA
      target: neoB
      kind: tag
      table_map: # table_map은 오직 1:1 사용 (source 와 target의 테이블 이름이 서로 다를 수 있으나 구조는 같음)
        source: tag
        target: tag
        columns: []
        seq_expr: RID # RID, TO_TIMESTAMP(time)
      options: # Opion 추가
        use_meta: false
        placement: none #prefix # prefix, suffix, regexp, none
        affix: svr1
        interval: 1m
        delay: 1m
        rid_limit : 1000
        batch_window_limit: 1h
      checkpoint: ./tmp/tag_to_log.chk

logging:
  level: INFO
  path: ./tmp/replication.log
  max_size: 20
  max_backups: 5
  max_age: 5
  compress: true
  mode: debug


# checkpoint에 source 와 target 같이 포함?

# confluence 작성
# config. yaml
# - child Page : config.yaml 에 대한 설명 (각 옵션에 대한 설명)
# - child Page : 프로세스 동작 구조 ( ex) 함수 이름 과 설명 & source -> transform -> target  각 동작 설명 ) 

# 신성델타 메타 컬럼 추가 후에 insert 시 "" 빈값 추가필요