replication:
  sources:
    - name: source_db1
      type: machbase
      connection:
        scheme: http
        host: 192.168.0.87
        port: 5654
        protocol : http
        token: xxx
      
    - name: source_db2
      type: machbase
      connection:
        scheme: http
        host: 192.168.0.99
        port: 5654
        protocol : http
        token: xxx
  
  targets:
    - name: target_db1
      type: machbase
      connection:
        scheme: http
        host: 192.168.0.87
        port: 5654
        protocol : http
        token: xxx

    - name: target_db2
      type: machbase
      connection:
        scheme: http
        host: 192.168.0.87
        port: 5654
        protocol : http
        token: xxx
  
  jobs:
    - name: tag_to_log
      source: source_db1
      target: target_db1
      kind: tag
      table_map: # table_map은 오직 1:1 사용 (source 와 target의 테이블 이름이 서로 다를 수 있으나 구조는 같음)
        source: gasan
        target: guro
        columns: [name, time, value, uuid]
        seq_expr: RID" # RID, TO_TIMESTAMP(time)
      options: # Opion 추가
        use_meta: true
        # placement: prefix # prefix, suffix, regexp
        # affix: svr1
        interval: "1m"
        delay: "10m"
        batch_window_limit: "1h"
      checkpoint: "./tmp/tag_to_log.chk"

    - name: mach_to_mach2
      source: source_db2
      target: target_db2
      kind: tag
      table_map:
        source: gasan
        target: guro
        columns: [name, time, value, uuid]
        seq_expr: "RID"
      options:
        placement: prefix # prefix, suffix, regexp
        affix: svr1
        interval: "1m"
        delay: "10m"
        batch_window_limit: "1h"
      checkpoint: "./tmp/mach_to_mach.chk"

logging:
  level: INFO
  path: ./tmp/replication.log
  max_size: 20
  max_backups: 5
  max_age: 5
  compress: true
  # mode: release
  mode: debug


# checkpoint에 source 와 target 같이 포함?

# confluence 작성
# config. yaml
# - child Page : config.yaml 에 대한 설명 (각 옵션에 대한 설명)
# - child Page : 프로세스 동작 구조 ( ex) 함수 이름 과 설명 & source -> transform -> target  각 동작 설명 ) 

# 신성델타 메타 컬럼 추가 후에 insert 시 "" 빈값 추가필요