replication:
  sources:
    - name: source_db1
      type: machbase
      connection:
        scheme: http
        host: 192.168.0.87
        port: 5654
      
    - name: source_db2
      type: machbase
      connection:
        scheme: http
        host: 192.168.0.99
        port: 5654
  
  targets:
    - name: target_db1
      type: machbase
      connection:
        scheme: http
        host: 192.168.0.87
        port: 5654

    - name: target_db2
      type: machbase
      connection:
        scheme: http
        host: 192.168.0.87
        port: 5654
  
  jobs:
    - name: tag_to_log
      source: source_db1
      target: target_db1
      table_map: # table 은 오직 1:1 사용 (source 와 target 의 db이름 서로 다를 수 있음)
        source: tag
        target: guro
        columns: [name, time, value, uuid]
      options: # Opion 추가
        interval: "1m"
        delay: "10m"
      checkpoint: "./tmp/tag_to_log.chk"

    - name: mach_to_mach2
      source: source_db2
      target: target_db2
      table_map:
        source: tag
        target: guro
        columns: [name, time, value, uuid]
      options:
        interval: "1m"
        delay: "10m"
      checkpoint: "./tmp/mach_to_mach.chk"

logging:
  level: INFO
  file: ./tmp/replication.log


# checkpoint에 source 와 target 같이 포함?

# confluence 작성
# config. yaml
# - child Page : config.yaml 에 대한 설명 (각 옵션에 대한 설명)
# - child Page : 프로세스 동작 구조 ( ex) 함수 이름 과 설명 & source -> transform -> target  각 동작 설명 ) 

# 신성델타 메타 컬럼 추가 후에 insert 시 "" 빈값 추가필요